### Slicing and Indexing


In [12]:
import numpy as np
array1 = np.array(([11,12,13,14], [21,22,23,24], [31,32,33,34]))
print(array1)
print(array1.shape)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
(3, 4)


* Using array slicling we can get the sub arry from the above array

In [7]:
sub_array = array1[:2, 1:3]
print(sub_array)

[[12 13]
 [22 23]]


In [10]:
#Now actually we will try to change the value in sliced array and it will reflect in main array too
print(array1[0,1])
sub_array[0,0]=1000
print(array1[0,1])

1000
1000


In [14]:
#To get the actual copy of the sub array we can do as
sub_array = np.array(array1[:2, 1:3])
print(sub_array)

[[12 13]
 [22 23]]


In [16]:
#If we try to change the value in the sub arrary the canges won't reflect the main array
print(array1[0,1])
sub_array[0,0]=1000
print(array1[0,1])

12
12


### Use both integer indexing and slice indexing

In [26]:
array1 = np.array(([11,12,13,14], [21,22,23,24], [31,32,33,34]))
print(array1)
print(array1.shape)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]
(4, 4)


In [19]:
#Using both ingeger indexing and slicing create a lower rank arry
row_rank = array1[1, :]
print(row_rank, row_rank.shape)

[21 22 23 24] (4,)


In [22]:
#Slicing alone generates the same rank as the original array
row_rank2 = array1[1:2, :]
print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [29]:
#Create a 4x4 array
array2 = np.array([[11,12,14,15], [21,22,23,24], [31,32,33,34], [41,42,43,44]])
print(array2, array2.shape)

#Create some row indeces
row_indeces = [0,1,2,3]

#Create some column indeces
col_indeces = [0,2,1,0]
print("Values in the array at those indeces are: ", array2[row_indeces, col_indeces])

#We can change the values at those indeces are easy as below
array2[row_indeces, col_indeces] += 10000
print(array2)

[[11 12 14 15]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]] (4, 4)
Values in the array at those indeces are:  [11 23 32 41]
[[10011    12    14    15]
 [   21    22 10023    24]
 [   31 10032    33    34]
 [10041    42    43    44]]
