* Nd Array boolean indexing
### Lets create an array


In [14]:
import numpy as np
an_array = np.array([[11,12], [21,22], [31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [4]:
#Create a filter with the condition that we want
filter1 = an_array>15
print(filter1)

[[False False]
 [ True  True]
 [ True  True]]


In [7]:
#We can apply the above created filter to check our data
filtered_data = an_array[filter1]
print(filtered_data)

[21 22 31 32]


In [8]:
# also we can create filter on the fly
print(an_array[an_array>25])

[31 32]


In [11]:
# We can also apply conditions on the array
even_age = an_array[an_array %2 ==0]
print(even_age)

#Selecting the age in a range
age_range = an_array[(an_array > 20) & (an_array<30)]
print(age_range)

[12 22 32]
[21 22]


In [15]:
# Increasing age 100 years for even numbers
print('Before increasing: ', an_array)
an_array[an_array %2 ==0] += 100
print('After increasing: ', an_array)

Before increasing:  [[11 12]
 [21 22]
 [31 32]]
After increasing:  [[ 11 112]
 [ 21 122]
 [ 31 132]]
