In [3]:
# Lets create a 2x4 matrix
import numpy as np
an_array = np.random.random([2,4])
print(an_array)

[[0.5942774  0.43674343 0.86441496 0.45126984]
 [0.71181623 0.82784263 0.44832994 0.61668929]]


In [5]:
#Lets get the mean of that array
mean = an_array.mean()
print(mean)

0.6189229668010029


In [7]:
# If we wanted to find the mean row wise 
r_mean = an_array.mean(axis=1)
print(r_mean)

[0.58667641 0.65116952]


In [10]:
#If we wanted to get the mean for column wise then
c_mean = an_array.mean(axis=0)
print(c_mean)

[0.65304682 0.63229303 0.65637245 0.53397957]


In [13]:
#Sum all the elements
print(an_array.sum())

4.951383734408023


In [26]:
a = np.array([[21,22,23,24], [31,32,33,34], [41,42,43,44]])
print(a)
print(a[-2:, -2:])

[[21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]
[[33 34]
 [43 44]]


In [28]:
#Computing the meadian
median = np.median(an_array, axis=1)
print(median)

[0.52277362 0.66425276]


### Sorting:


In [30]:
un_sorted = np.random.randn(10)
print(un_sorted)

[-2.3430289  -0.77378877  0.1801945  -0.45579138  0.80811593  0.44354606
  1.19905778  0.58590234  1.04528137  0.19715032]


In [33]:
#Before sorting this array let's copy it
sorted = np.array(un_sorted)
sorted.sort()
print(sorted)
print(un_sorted)

[-2.3430289  -0.77378877 -0.45579138  0.1801945   0.19715032  0.44354606
  0.58590234  0.80811593  1.04528137  1.19905778]
[-2.3430289  -0.77378877  0.1801945  -0.45579138  0.80811593  0.44354606
  1.19905778  0.58590234  1.04528137  0.19715032]


### Finding unique elements

In [35]:
arr = np.array([2,3,4,3,2,5,3,4,2])
print(np.unique(arr))

[2 3 4 5]


### Set operations with np.array data type

In [37]:
s1 = np.array(['desk', 'chair', 'bulb'])
s2 = np.array(['lamp', 'bulb', 'chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [39]:
#Get intersect
print(np.intersect1d(s1, s2))

['bulb' 'chair']


In [41]:
#Get union
print(np.union1d(s1, s2))

['bulb' 'chair' 'desk' 'lamp']


In [43]:
#Elements in s1 that are not in s2
print(np.setdiff1d(s1, s2))

['desk']


In [45]:
#Elements in s1 that are also in s2
print(np.in1d(s1, s2))

[False  True  True]
