### Creating Rank1 arrays


In [1]:
import numpy as np

vec = np.array([3,33,333])
print(type(vec))

<class 'numpy.ndarray'>


In [2]:
#To get the shape of the array that we just created above which is having only one dimension
print(vec.shape)

(3,)


In [3]:
#For creating Rank2 arrays
twoD = np.array([[11,12,13], [21,22,23]])
print("twoD array shape is:", twoD.shape)

twoD array shape is: (2, 3)


In [7]:
#To fill the elements with zeros we can do as
zeros = np.zeros((2,2))
print(zeros)

[[0. 0.]
 [0. 0.]]


In [12]:
#To fill with perticular values of a given size
nines = np.full((3,4), 9)
print(nines)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [16]:
#To create a 2x2 matrix and  fill the values 1's diagnolly and 0's remaining 
print(np.eye(2,2))

[[1. 0.]
 [0. 1.]]


In [20]:
#To create a matrix with all the one as values
print(np.ones((2,3), dtype=int))

[[1 1 1]
 [1 1 1]]


In [21]:
#For creating random values in a matrix
rand_array = np.random.random((2,3))
print(rand_array)

[[0.84172355 0.75371997 0.75669053]
 [0.40091417 0.40414855 0.53011115]]
